name: Build and Deploy Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 1] checkout repo
        uses: actions/checkout@v2
        with:
          ref: main
          submodules: recursive
          clean: true
          fetch-depth: 1
          lfs: false
      
      - name: 2] Build pages with jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: .
          destination: ./_site
          future: false
          verbose: true
          
      - name: 3] Archive build output
        run: tar --dereference --hard-dereference --directory _site/ -cvf artifact.tar .
        shell: bash
      
      - name: 4] upload artifact
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: ./artifact.tar
          if-no-files-found: warn

          
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy pages
        uses: actions/deploy-pages@v1
        with:
          timeout: 400000
          error_count: 4
          reporting_interval: 1000
